### ISSUE TITLE
Change config to have an attribute called 'properties'

### ISSUE THREAD

**Issue by camratchford** [camratchford/MSICompiler#3]
This 'properties' attribute is a dictionary of every non-required field that we can feed to the MSI property table.

See Windows Installer documentation [here](https://learn.microsoft.com/en-us/windows/win32/msi/property-reference)

For example, we currently feed the following into the properties table, and each have their own config attribute:
- company
- contact_email
- webpage
- upgrade_code

The new config topology would have those under one attribute 'properties'

```yaml
properties:
  company: 'RatchfordConsulting'
  contact_email: 'camratchford@gmail.com'
  webpage: 'https://support.ratchfordconsulting.com/'
  upgrade_code: '{39CFB886-7C1D-4469-A9C1-0C578E1C36D8}'
```
