### ISSUE TITLE
Add ability to specify more than 1 custom action

### ISSUE THREAD

**Issue by camratchford** [camratchford/MSICompiler#5]
- Change config to allow a list of dict objects containing the name, action type, and the action target
  - The order in which they appear in the config / cli will dictate the sequence id of the action
  - Each 'type' will correspond to a predefined (and known to be working) set of variables that the `compiler.add_custom_action` function will implement.

```yaml
custom_actions:
  - name: RunScript
    type: powershell
    target: script.ps1
    args: []
  - name: SetPATH
    type: executable
    target: c:\windows\system32\setx.exe
    args:
      - PATH
      - "%PATH%;%USERPROFILE%\bin"
```
