### ISSUE TITLE
Implement writeenvironmentstrings standard action

### ISSUE THREAD

**Issue by camratchford** [camratchford/MSICompiler#7]
Link [here](https://learn.microsoft.com/en-us/windows/win32/msi/writeenvironmentstrings-action)

Implement a config attr and corresponding function for each of the following:
- Append to environment variable
```
environment_variables:
  - name: PATH
    value: 'C:\ProgramFiles\MyApp\bin\'
    mode: append
    delimiter: ';'
```

- Add environment variable
```
environment_variables:
  - name: MYAPP_HOME
    value: 'C:\ProgramFiles\MyApp\'
    mode: add
    # no delimiter required, any value will be ignored
```

- Remove environment variable
```
environment_variables:
  - name: DEPRICATED_MYAPP_VAR
    # no value required, any entry will be ignored
    mode: remove
    # no delimiter required, any entry will be ignored
```
