### ISSUE TITLE
Implement WriteRegistryValues action

### ISSUE THREAD

**Issue by camratchford** [camratchford/MSICompiler#8]
Link [here](https://learn.microsoft.com/en-us/windows/win32/msi/writeregistryvalues-action)

- Ensure that hex and octal values are converted to decimal and that only decimal values are fed into the action data
- Ensure that registry paths do not start or begin with backslashes before they are fed into the action data

Create config attr and corresponding functions for the following:

- Add registry key
```yaml
registry_keys:
  - path: 'HKEY_LOCAL_MACHINE\SOFTWARE\MyApp'
    name: 'LicenseKey'
    value: '[UpgradeKey]'
    mode: add
```

- Remove registry key
```yaml
registry_keys:
  - path: 'HKEY_LOCAL_MACHINE\SOFTWARE\MyApp'
    name: 'LicenseKey'
    value: '[UpgradeKey]'
    mode: remove
```
